'use strict'
let userName= prompt("What's your name?")
console.log(userName)
console.log(typeof userName)
let favSong = prompt("whats your favorite song for KALEO?")
console.log(favSong)
console.log(typeof favSong)
let favSinger = prompt("who's your favorite singer beside KALEO?")
console.log(favSinger)
console.log(typeof favSinger)
let whichOne = prompt("SKINNY OR BACKBONE?")
console.log(whichOne)
console.log(typeof whichOne)
alert('welcome'+userName+"your favorite song is"+ favSong +",good choice" +favSinger+"is a good singer too"+whichOne+"thats a great song!!")
